### ISSUE TITLE
Error while executing main

### ISSUE THREAD

**Issue by Taliayaya** [rigobert9/AnkiAutoCards#2]
### Description

After cloning the project and executing it, it fails : 
`File "ankiantocards", line 164, in <module> main(),
File "ankiautocards", line 161, in main args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
`

I verified that every packages were up to date. 
Any idea ?

**Comment by rigobert9** [comment]
Have you installed aqt ?
Also a patch just dropped

**Comment by Taliayaya** [comment]
I have updates on this bug. 

It's when you don't use any arguments :
```sh
python ankiautocards
```
will create this error
> `File "ankiantocards", line 164, in <module> main(), File "ankiautocards", line 161, in main args.func(args) AttributeError: 'Namespace' object has no attribute 'func' `

while 
```sh
python ankiautocards -h
```
will print the help output.

I think if no arguments are given, it should also shows the help ouput.
